services:
  orders:
    build:
      context: .
      dockerfile: src/Publishing.Orders.Service/Dockerfile
    ports:
      - "5001:80"
    environment:
      - DB_CONN=${DB_CONN}
      - REDIS_CONN=${REDIS_CONN}
      - RABBIT_CONN=${RABBIT_CONN}
      - JWT__Issuer=${JWT__Issuer}
      - JWT__Audience=${JWT__Audience}
      - JWT__SigningKey=${JWT__SigningKey}
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_started
      organization:
        condition: service_healthy
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - micro-net

  profile:
    build:
      context: .
      dockerfile: src/Publishing.Profile.Service/Dockerfile
    ports:
      - "5002:80"
    environment:
      - DB_CONN=${DB_CONN}
      - REDIS_CONN=${REDIS_CONN}
      - JWT__Issuer=${JWT__Issuer}
      - JWT__Audience=${JWT__Audience}
      - JWT__SigningKey=${JWT__SigningKey}
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_started
      organization:
        condition: service_healthy
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - micro-net

  organization:
    build:
      context: .
      dockerfile: src/Publishing.Organization.Service/Dockerfile
    ports:
      - "5003:80"
    environment:
      - DB_CONN=${DB_CONN}
      - REDIS_CONN=${REDIS_CONN}
      - JWT__Issuer=${JWT__Issuer}
      - JWT__Audience=${JWT__Audience}
      - JWT__SigningKey=${JWT__SigningKey}
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_started
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost/health || exit 1"]
      interval: 10s
      timeout: 5s
      start_period: 30s
      retries: 5
    networks:
      - micro-net

  gateway:
    build:
      context: .
      dockerfile: src/ApiGateway/Dockerfile
    ports:
      - "5000:80"
    environment:
      - REDIS_CONN=${REDIS_CONN}
      - JWT__Issuer=${JWT__Issuer}
      - JWT__Audience=${JWT__Audience}
      - JWT__SigningKey=${JWT__SigningKey}
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      orders:
        condition: service_healthy
      profile:
        condition: service_healthy
      organization:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - micro-net

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=${ACCEPT_EULA}
      - SA_PASSWORD=${SA_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pidof sqlservr"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "1433:1433"
    volumes:
      - db-data:/var/opt/mssql
    networks:
      - micro-net

  cache:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - micro-net

  rabbit:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - micro-net

networks:
  micro-net:
    driver: bridge

volumes:
  db-data:
  redis-data:
