groups:
- name: publishing-alerts
  rules:
  - alert: HighErrorRate
    expr: rate(http_server_requests_seconds_count{status!~"2.."}[1m]) > 0.1
    for: 2m
    labels:
      severity: warning
    annotations:
      summary: High error rate
      description: More than 10% of requests are failing.
