name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Install EF Core CLI
      run: dotnet tool install --global dotnet-ef --version 6.0.*
    - name: Add dotnet-ef to PATH
      run: echo "${{ env.USERPROFILE }}\\.dotnet\\tools" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
    - name: Restore
      run: dotnet restore
    - name: Apply EF migrations
      run: dotnet ef database update --project src/Publishing.Infrastructure
    - name: Build
      run: dotnet build --no-restore
    - name: Format
      run: dotnet format --no-restore --verify-no-changes
    - name: Test
      run: dotnet test --no-build --collect:"XPlat Code Coverage" --results-directory ./TestResults /p:Threshold=80 /p:ThresholdType=line /p:ThresholdStat=total
