name: Deploy to Kubernetes

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: v1.28.0
      - name: Decode kubeconfig
        run: echo "$KUBE_CONFIG_DATA" | base64 -d > kubeconfig
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
      - name: Deploy manifests
        run: kubectl apply -f k8s/
        env:
          KUBECONFIG: kubeconfig
