name: Organization Service CI

on:
  push:
    paths:
      - 'src/Publishing.Organization.Service/**'
  pull_request:
    paths:
      - 'src/Publishing.Organization.Service/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: Check JWT env vars
        run: |
          test -n "${{ secrets.JWT__SigningKey }}" && \
          test -n "${{ secrets.JWT__Issuer }}" && \
          test -n "${{ secrets.JWT__Audience }}"
      - name: Restore
        run: dotnet restore src/Publishing.Organization.Service/Publishing.Organization.Service.csproj
      - name: Build
        run: dotnet build src/Publishing.Organization.Service/Publishing.Organization.Service.csproj --no-restore
      - name: Test
        run: dotnet test src/tests/Publishing.Core.Tests/Publishing.Core.Tests.csproj --no-build
      - name: Test Integration
        run: dotnet test src/tests/Publishing.Integration.Tests/Publishing.Integration.Tests.csproj --no-build
      - name: Build container
        env:
          DB_CONN: ${{ secrets.DB_CONN }}
          REDIS_CONN: ${{ secrets.REDIS_CONN }}
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/organization-service src/Publishing.Organization.Service
      - name: Login & Push
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push ${{ secrets.DOCKER_USERNAME }}/organization-service
        env:
          DB_CONN: ${{ secrets.DB_CONN }}
          REDIS_CONN: ${{ secrets.REDIS_CONN }}
