name: Profile Service CI

on:
  push:
    paths:
      - 'src/Publishing.Profile.Service/**'
  pull_request:
    paths:
      - 'src/Publishing.Profile.Service/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: Check JWT env vars
        run: |
          test -n "${{ secrets.JWT__SigningKey }}" && \
          test -n "${{ secrets.JWT__Issuer }}" && \
          test -n "${{ secrets.JWT__Audience }}"
      - name: Restore
        run: dotnet restore src/Publishing.Profile.Service/Publishing.Profile.Service.csproj
      - name: Build
        run: dotnet build src/Publishing.Profile.Service/Publishing.Profile.Service.csproj --no-restore
      - name: Test
        run: dotnet test src/tests/Publishing.Core.Tests/Publishing.Core.Tests.csproj --no-build
      - name: Test Integration
        run: dotnet test src/tests/Publishing.Integration.Tests/Publishing.Integration.Tests.csproj --no-build
      - name: Build container
        env:
          PROFILE_DB_CONN: ${{ secrets.PROFILE_DB_CONN }}
          REDIS_CONN: ${{ secrets.REDIS_CONN }}
          CONSUL_URL: ${{ secrets.CONSUL_URL }}
          OIDC_AUTHORITY: ${{ secrets.OIDC_AUTHORITY }}
          OIDC_AUDIENCE: ${{ secrets.OIDC_AUDIENCE }}
          ELASTIC_URL: ${{ secrets.ELASTIC_URL }}
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/profile-service -f src/Publishing.Profile.Service/Dockerfile .
      - name: Login & Push
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push ${{ secrets.DOCKER_USERNAME }}/profile-service
        env:
          PROFILE_DB_CONN: ${{ secrets.PROFILE_DB_CONN }}
          REDIS_CONN: ${{ secrets.REDIS_CONN }}
          CONSUL_URL: ${{ secrets.CONSUL_URL }}
          OIDC_AUTHORITY: ${{ secrets.OIDC_AUTHORITY }}
          OIDC_AUDIENCE: ${{ secrets.OIDC_AUDIENCE }}
          ELASTIC_URL: ${{ secrets.ELASTIC_URL }}
